### ISSUE TITLE
Inertiajs

### ISSUE THREAD

**Issue by bajki** [socotecio/vue-datatable-url-sync#3]
Can it be used with inertia?

**Comment by AMontagu** [comment]
It can work with any datatable as soon as you use Vue.js.

If you need help to start you can provide me an example repository to help you.

**Comment by bajki** [comment]
https://github.com/xalunda/inertiajs-laravel-vuetify/blob/master/resources/js/Components/Shared/DataTableWrapper.vue

Lets say this is my datatable and i want to sync search and sortBy,

**Comment by AMontagu** [comment]
Okay so the issue here with this components is that it doesn't emit the search value.
But if you overide it you can use it.
Example:
https://github.com/socotecio/vue-datatable-url-sync/blob/example/inertia/vue2-example/src/components/InertiaDatatable.vue

If you want to component to be reactive of sortBy and SortDesc when the props change just add a watcher on it.

**Comment by AMontagu** [comment]
close due to inactivity
